name: Livedoor Auto Post

on:
  schedule:
    - cron: '0 0 * * *' # 毎日 日本時間AM9時に自動実行
  workflow_dispatch: # ← コレがボタンを出す魔法の呪文です！

jobs:
  post-blog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests feedparser

    - name: Run script
      env:
        LIVEDOOR_ID: ${{ secrets.LIVEDOOR_ID }}
        LIVEDOOR_KEY: ${{ secrets.LIVEDOOR_KEY }}
        BLOG_ID: ${{ secrets.BLOG_ID }}
      run: python poster.py
